language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t sugawarayushin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sugawarayushin/react-test npm test

after_success:
  - docker build -t sugawarayushin/multi-client ./client
  - docker build -t sugawarayushin/multi-nginx ./nginx
  - docker build -t sugawarayushin/multi-server ./server
  - docker build -t sugawarayushin/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sugawarayushin/multi-client
  - docker push sugawarayushin/multi-nginx
  - docker push sugawarayushin/multi-server
  - docker push sugawarayushin/multi-worker
  
